### ISSUE TITLE
Printf is not supported on Arduino

### ISSUE THREAD

**Issue by rlb222** [Stutchbury/EncoderButton#11]
The Serial.printf command in your README.md file is not supported. 
These commands you have already altered in the (Basic) example. But I followed the README.md first, and ran into this.

**Comment by Stutchbury** [comment]
Good spot! I have updated the README: https://github.com/Stutchbury/EncoderButton/commit/abd16fe0a67bd520e869730732adae17632f1a41

Many thanks

**Comment by rlb222** [comment]
🙏🏻—//—Op 19 jun 2024 om 11:46 heeft Philip Fletcher ***@***.***> het volgende geschreven:﻿
Good spot! I have updated the README.
abd16fe
Many thanks
