### ISSUE TITLE
The Bounce2 header changed its duration() method to currentDuration()

### ISSUE THREAD

**Issue by jackmill** [Stutchbury/EncoderButton#2]
It looks like the duration() method in the Debouncer class from Bounce2.h changed to currentDuration() a few months ago, so this library doesn't compile.

**Comment by Stutchbury** [comment]
Well that's a little frustrating - it would seem the latest Bounce2 release (v2.60) that is available in the Arduino Library Manager is a couple of commits behind the github master.
I will raise an issue with Thomas Fredericks to request a new release.
Thank you for the heads up - for now I will remain aligned to the latest Bounce2 release.
