### ISSUE TITLE
Issues with callbacks when encoder's button is pressed and rotated at the same time

### ISSUE THREAD

**Issue by leon-gh** [Stutchbury/EncoderButton#7]
I've started using EncoderButton library for my home project and noticed strange behavior when encoder's button is pressed and encoder is rotated at the same time. I have it connected to a joystick button and I use setPressedHandler and setReleasedHandler to press/release a joystick button. When I press encoder's button and rotate the encoder (happened by mistake the first time) the joystick button gets pressed and never released. If I press the encoder's button again, then the joystick button would also get released.

NOTE, I've also setup idle and click handler. They do nothing, except print they were called. 
state in the log is the eb.buttonState() and BL is the name of the encoder. The presses were all short presses.

Log when I press and release the button:
```
17:25:44.471 -> encoder_button_pressed BL, state: 0
17:25:44.566 -> encoder_button_released BL, state: 1
17:25:44.800 -> encoder_button_click BL, state: 1
17:25:45.553 -> rotary_encoder_idle BL, state: 1
```

Log when I press, rotate the encoder, and release button:
```
17:25:52.042 -> encoder_button_pressed BL, state: 0
17:25:53.690 -> rotary_encoder_idle BL, state: 1
```
I think here there's something wrong. I would be expecting a callback encoder_button_released.

Log when I press, and release the button after the encoder is in 'bad state':
```
17:28:07.627 -> encoder_button_pressed BL, state: 0
17:28:07.720 -> encoder_button_released BL, state: 1
17:28:07.955 -> encoder_button_click BL, state: 1
17:28:08.709 -> rotary_encoder_idle BL, state: 1
```

I checked the code and it looks like there are two counted positions for rotations - normal, when button is depressed and pressed. I suspect there's something wrong with the pressed position counter/events.

Please let me know if I'm doing something wrong.

Thank you and BTW, very good job on the lib!

**Comment by Stutchbury** [comment]
Hi Leon

Could you please provide a minimal sketch that demonstrates the issue?

Many thanks

**Comment by leon-gh** [comment]
Hi,

I realized I didn't have setEncoderPressedHandler  and setEncoderReleasedHandler  setup. Let me add them and if I see the issue I'll attach the sketch, otherwise let you know to close this issue.

**Comment by leon-gh** [comment]
I just did a test and it looks like that setting up setEncoderPressedHandler and setEncoderReleasedHandlerhandlers solves the issue for me. My issue was that I used button's callback for encoder button, which is wrong usage of the library.

Maybe worth adding a note to documentation that setPressedHandler that setReleasedHandler should not be used for encoder buttons, even though they are technically buttons :-). 

There's no issue with the library - thanks again for good work, closing this issue as invalid.

**Comment by Stutchbury** [comment]
Thanks for the feedback Leon - Pressed and Released can be used for encoder buttons - Pressed will always fire but Released will only fire if the encoder is not turned (while pressed). EncoderPressed and EncoderReleased  are only fired if the the button is pressed *and* turned. 
ie Pressed, [EncoderPressed, EncoderReleased]|Released.
Possibly need a flow diagram in the docs!
